# -*- coding: utf-8 -*-
"""Copy of LifeExpectancyLinearRegressionStarter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcYbCPI0ohYR1o9hDkhs0p_i1CzJssUr
"""

"""
Dataset: https://www.kaggle.com/kumarajarshi/life-expectancy-who

Build a linear regression model and a polynomial regression model that predicts the life expectancy of a person based on their characteristics. Determine which model best fits the data.
"""

import pandas as pd


filepath = 'https://static.junilearning.com/ai_level_2/life_expectancy.csv'
# dataset: https://www.kaggle.com/kumarajarshi/life-expectancy-who
data = pd.read_csv(filepath)
data = data.drop('Country', axis=1)
data = data.drop('Status', axis=1)
data.dropna(inplace=True)
