# -*- coding: utf-8 -*-
"""Copy of NeuralNetworksHousePriceRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MNM2R2Ia7FkO_uWq4hcX-EBMN2RQC8gA
"""

"""
Dataset: https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html

Use the keras package and neural networks to build a regression model that predicts the prices of houses based on the characteristics of the house and its neighborhood.
"""

import matplotlib.pyplot as plt
from keras import Sequential
from keras.datasets import boston_housing
from keras.layers import Dense
from sklearn.preprocessing import StandardScaler


# load dataset and split into training and testing data
# Dataset Info: https://www.cs.toronto.edu/~delve/data/boston/bostonDetail.html
(x_train, y_train), (x_test, y_test) = boston_housing.load_data()

# normalize data
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Regression model with a neural network
model = Sequential()
model.add(Dense(8, input_dim=13, activation='relu'))  # input_dim = size of feature vector
model.add(Dense(16, activation='relu'))
model.add(Dense(1))

# mse = mean squared error, mae = mean absolute error
model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])

# split into validation and training data and train model
history = model.fit(x_train, y_train, epochs=100)

# plot mean absolute error of training data
plt.plot(history.history['mae'])
plt.xlabel('epoch')
plt.show()

# first value is mse (average error)
# second value is mae (median error)
model.evaluate(x_test, y_test)

# plot predictions and actual values of test data
y_pred = model.predict(x_test).flatten()
plt.scatter(y_test, y_pred)
plt.xlabel('True Values [MEDV]')
plt.ylabel('Predictions [MEDV]')
lims = [0, 50]
plt.plot(lims, lims)
plt.show()
